import './globals.css'
import { Inter } from 'next/font/google'
import {NextIntlClientProvider, useLocale} from "next-intl";
import {notFound} from "next/navigation";
import Header from "@/components/header";
import {usePathname} from "next-intl/client";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children, params
}: {
  children: React.ReactNode
  params: any
}) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  // if (params.locale !== locale) {
  //   console.log(params.locale, locale)
  //   notFound();
  // }

  let messages;
  try {
    messages = (await import(`../locales/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  // const pathname = usePathname();
  console.log(params)

  return <html lang={locale}>
    <body className={inter.className}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Header></Header>
        {children}
      </NextIntlClientProvider>
    </body>
  </html>;
}
