import "./globals.css";

import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { ReactElement } from "react";

import Header from "@/components/header";
import { Providers } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: {
	children: ReactElement;
	params: any;
}) {
	const locale = useLocale();

	// Show a 404 error if the user requests an unknown locale
	// if (params.locale !== locale) {
	//   console.log(params.locale, locale)
	//   notFound();
	// }

	let messages;
	try {
		const file = await import(`../locales/${locale}.json`);
		messages = file.default;
	} catch {
		notFound();
	}

	return (
		<html lang={locale}>
			<body className={inter.className}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<Providers>
						<Header></Header>
						{children}
					</Providers>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
