import "./globals.css";

import { PropsWithChildren } from "react";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
	return <>{children}</>;
}
